import { Heebo } from "next/font/google";
import "./globals.css";

const heebo = Heebo({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio | Otto Gugel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${heebo.className} bg-surface`}>{children}</body>
    </html>
  );
}
